In [ ]:
import numpy as np
import pandas as pd

# Basic Local Search

In [ ]:
def generate_neighbors(cost_dict , x, y, right_cost, down_cost, left_cost, up_cost):
    
    cost_dict[right_cost] = [x , y+1]
    cost_dict[down_cost] = [x+1 , y]
    cost_dict[left_cost] = [x , y-1]
    cost_dict[up_cost] = [x-1 , y]
    
    return cost_dict

def check_constraints(arr , x, y):
    
    cost_dict = {}
    
    # right
    right_cost = arr[x][y+1] if y+1 <= 3 else -1
    
    # down
    down_cost = arr[x+1][y] if x+1 <= 3 else -1
        
    # left
    left_cost = arr[x][y-1] if y-1 >= 0 else -1
        
    # up
    up_cost = arr[x-1][y] if x-1 >= 0 else -1
    
    # adding neighbours in dictionary
    #cost_dict empty
    #x,y current val 
    #exploring the nigh  - val xy directions , cost key 

    cost_dict = generate_neighbors(cost_dict , x, y, right_cost, down_cost, left_cost, up_cost)
    
    return cost_dict, max(right_cost, down_cost, left_cost, up_cost)

def objective(count):
    print('Count =',count)
    sum_value = int(count*(count+1)/2)
    cost = (profit)*sum_value/16 - sum_value
    
    return int(cost)
        

In [ ]:

arr = [[0 , 0 , 0 , 0],
       [0 , -1 , 0 , -1],
       [0 , 5 , 0 , 0],
       [2 , 0 ,2 , 100]]

result = [[0,0,0,0],
          [0,0,0,0],
          [0,0,0,0],
          [0,0,0,0]]

row, col = 0 , 0
result[row][col] = 1 #WHENever i pass particolar row col i add 1 and the cont inithlaise by 2 becuse i alrady add 1 to the initial pos
count = 2

print("Initial Position ")
print(np.matrix(result))
print("----------------------")

print("Paths are following..")

profit = 0
while True: # to check the cons
    cost_dict , max_cost = check_constraints(arr , row, col)# 2d arr , intial val - return the cost dic
    arr[row][col] = -1 # tryverce avoid moving forward to replace the corrent vlaue to -1 this show that i have already vist the block , when alg move again to the same block it consider it alreadyvisted 
    row = cost_dict[max_cost][0] #for x exis
    col = cost_dict[max_cost][1]# for y exis  to get the max cost where present
    
    if max_cost == 100 or max_cost == -1: 
        if max_cost == 100:
             result[row][col] = count
        if max_cost == -1:
            count -= 1 #if it stuck it has greater val so decremnt 
        break 
    else:
        result[row][col] = count #ubdate cont in each iteration 
        count += 1 #whenever there is a pos to move from the current pos the count upd and its replase to the right row col 
        profit += arr[row][col]
        print(profit)
    print(np.matrix(result), "\n")
        

print("objective function value is: ", objective(count))
np.matrix(result)

Initial Position 
[[1 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
----------------------
Paths are following..
0
[[1 0 0 0]
 [2 0 0 0]
 [0 0 0 0]
 [0 0 0 0]] 

0
[[1 0 0 0]
 [2 0 0 0]
 [3 0 0 0]
 [0 0 0 0]] 

5
[[1 0 0 0]
 [2 0 0 0]
 [3 4 0 0]
 [0 0 0 0]] 

5
[[1 0 0 0]
 [2 0 0 0]
 [3 4 0 0]
 [0 5 0 0]] 

7
[[1 0 0 0]
 [2 0 0 0]
 [3 4 0 0]
 [0 5 6 0]] 

Count = 7
objective function value is:  -15


matrix([[1, 0, 0, 0],
        [2, 0, 0, 0],
        [3, 4, 0, 0],
        [0, 5, 6, 7]])